/*
 * File: app/store/SnapPictures.js
 * Date: Thu Feb 07 2013 14:08:00 GMT+0900 ( (W))
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('album.store.SnapPictures', {
    extend: 'Ext.data.Store',

    requires: [
        'album.model.Picture'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            storeId: 'MyJsonStore2',
            model: 'album.model.Picture',
            proxy: {
                type: 'ajax',
                url: 'data/snaps.json',
                reader: {
                    type: 'json',
                    root: 'data'
                }
            }
        }, cfg)]);
    }
});